# Generated by Django 5.2.17 on 2026-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_adminotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
